# Generated by Django 5.1 on 2024-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_recipe_blog_alter_recipe_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="blog",
            field=models.TextField(),
        ),
    ]
